### ISSUE TITLE
cuffdiff still references iget

### ISSUE THREAD

**Issue by mwvaughn** [iPlantCollaborativeOpenSource/dnalc_fAPI_apps#1]
I was reviewing the cuffdiff.sh file and noticed that it still references use of iget to dynamically grab the annotations for some species. I don't have an easy solution at hand but iget is specifically blocked by the Agave environment as a security risk.

**Comment by deardooley** [comment]
This is a good opportunity to use the enquote and argument feature to strip out all the boilerplate and use list assignments to shrink the script by at least 60% and delegate the file staging to Agave. This must have burned a disturbing number of cycles on data transfer...glad we're fixing it now.

**Comment by mwvaughn** [comment]
Yes, all the igets are being removed! This one is way at the end of the script, and I wanted to highlight it.

**Comment by deardooley** [comment]
Swap out the iget with a postit to stage in the file

OR

Use a heartbeat notification to kick off the sort in situ with a sidekick process.

OR 

Break it out as a post-processing step using the transform service.

OR 

Just stage the data in every time just in case.

—
Rion

**Comment by johnfonner** [comment]
Matt made the files referenced by the iget command public.  In commit 9fc3582, we switch to wget (since the files are public), which should close this issue.
